[package]
name = "Pinput"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.5"
proc-maps = "0.1.9"
libproc = "0.10.0"
process-memory = "0.4.0"
